name: bench

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  schedule:
    - cron: '0 9 * * 5'
  workflow_dispatch:

jobs:
  run-bench:
    name: run-benchmark-on-${{matrix.channel}}
    strategy:
      matrix:
        name:
          - rust-stable
          - rust-nightly
        include:
          - name: rust-stable
            channel: stable
          - name: rust-nightly
            channel: nightly
    runs-on: ubuntu-latest
    steps:
      - name: checkout-${{matrix.channel}}
        uses: actions/checkout@v3
      - name: setup-toolchain-${{matrix.channel}}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.channel}}
          override: true
          components: rustfmt
      - name: cargo-build-${{matrix.channel}}
        run: cargo build
      - name: cargo-check-${{matrix.channel}}
        run: cargo check
      - name: cargo-bench-${{matrix.channel}}
        run: cargo bench
      - name: upload-bench-results-${{matrix.channel}}
        uses: actions/upload-artifact@v1
        with:
          name: azamcodec_bench_${{matrix.channel}}_${{github.sha}}
          path: ./target/criterion
