name: benchmark

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    - opened
    - reopened
    - synchronize # 'synchronize' is when BASE is sync'd with HEAD
  schedule:
    - cron: '0 9 * * 5' # 9am UTC every Friday
  workflow_dispatch:

jobs:
  run-benchmark:
    name: run-benchmark-on-${{matrix.channel}}
    strategy:
      matrix:
        name:
          - rust-stable
          - rust-nightly
        include:
          - name: rust-stable
            channel: stable
          - name: rust-nightly
            channel: nightly
    runs-on: ubuntu-latest
    steps:
      - name: checkout-${{matrix.channel}}
        uses: actions/checkout@v3
      - name: setup-toolchain-${{matrix.channel}}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{matrix.channel}}
          override: true
          components: rustfmt
      - name: cargo-build-${{matrix.channel}}
        run: cargo build
      - name: cargo-check-${{matrix.channel}}
        run: cargo check
      - name: cargo-bench-${{matrix.channel}}
        run: cargo bench
      - uses: actions/upload-artifact@v1
        with:
          name: azamcodec_${{github.sha}}_bench
          path: ./target/criterion # Upload benchmark result as workflow artifact
